default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'sqlite3' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: utf8
  pool: 5
  timeout: 5000
  connect_timeout: 10

development:
  <<: *default
  #database: lti_tool_provider_example_development
  database: db/development.sqlite3

test:
  <<: *default
  #database: lti_tool_provider_example_test
  database: db/test.sqlite3

production:
  <<: *default
  #database: lti_tool_provider_example_production
  database: db/test.sqlite3
